spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mfa?createIfNotExit=true?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_empty

  mail:
    username: binodnakhan95@gmail.com
    host: smtp.gmail.com
    port: 587
    password: yxqngqyjriikbfci
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAJ128Bl5GAHfOqdukLgfEeteM8maFt/n0C/aTyF4/wxC0tBJHSbpvTdgcliUQ4yZgAixXAXpZABY0/sw6yFRIN9nCWlLdLutZZuv6HHdmLXiRKsBUQ5YupDztP8z/IBBSd98aSKoxzgiPK442+Q3AYPTG9RckbDgeqEbXpMgWVWVAgMBAAECgYBr7HcHnn2b2toio59A8tqfTUOFa7093W5NPf16XanBR5Oh+lqmrxFnAQ2eNJBPr22Xh6ggzSQjML6prY+amDZEk3NMLjkUA9MhjNdfjaHWTeT7Xhf5vj1BcxKrwblRUVRQXZTdgy4Z/FyegTUqfV9+RZkc/CvWh50aReNZYlhXgQJBAN6hU4zBMB0U8OzKMo0GK6CI1eT8c8Kmul6ZTStO8lZ3vBTFIfCxuzdA71/TZt6Vl+uYFhZXeSrTRXctUCQwx9ECQQC1ERrPAWhEyCOHq2HETiwD3dDUgCWxYfofCpTc3gDvs5eIqqdAaavGUnvHm03+JSlNV2Nf/q3TEGhbRERmcKaFAkBuitIueJpIRmaeXIOfLGorKuZx7bwY8apmYF5F28xOjONRuNRya/2WoOJ6xUA10zd83qZQ75wVXJQIafJ6FdKRAkAxGGQ2gOEu1T2dCcFGoxOYMMrw85ZE1JYnWI0oniGO3RlXez5CXuSur6rUYq3xHU5npCxT2RB0zFwfcxFA3YapAkBAEigkBtYP7lpATUaFejINvsV8/E6eRVBo1dKqx9h4gkIqdFsF9nm1LtarspguEl+lFKkxXfXU/awzxM7/YKDa
server:
  port: 8000

